#!/usr/bin/env bash
# Install the Xulu CLI (Linux x86_64) from GitHub Releases.
#
# Recommended (applies PATH in your current shell too):
#   curl -fsSL https://raw.githubusercontent.com/xuluhq/xulu/master/install.sh | bash && . ~/.local/share/xulu/env.sh && hash -r
#
# Optional:
#   XULU_VERSION=v0.1.0 bash install.sh   # pin a release tag
#   INSTALL_DIR=~/.local/bin bash install.sh
#
# Note: `curl | bash` alone cannot change your interactive shell's PATH (child process).
# The trailing `. ~/.local/share/xulu/env.sh` runs in your shell and fixes that.

set -euo pipefail

REPO="xuluhq/xulu"
ASSET="xulu-linux-x86_64"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/.local/bin}"
VERSION="${XULU_VERSION:-}"
PATH_LINE="export PATH=\"${INSTALL_DIR}:\$PATH\""
ENV_FILE="${HOME}/.local/share/xulu/env.sh"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: '${1}' is required" >&2
    exit 1
  fi
}

path_contains_install_dir() {
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) return 0 ;;
    *) return 1 ;;
  esac
}

default_rc_file() {
  case "${SHELL##*/}" in
    zsh) echo "${HOME}/.zshrc" ;;
    bash) echo "${HOME}/.bashrc" ;;
    *) echo "${HOME}/.bashrc" ;;
  esac
}

ask_yes_no() {
  local prompt="$1"
  local reply
  # When installed via `curl | bash`, stdin is the script — read from the terminal.
  if [[ -r /dev/tty ]]; then
    printf "%s" "${prompt}" > /dev/tty
    read -r reply < /dev/tty
  elif [[ -t 0 ]]; then
    printf "%s" "${prompt}"
    read -r reply
  else
    echo "n"
    return 1
  fi
  case "${reply}" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

write_env_file() {
  mkdir -p "$(dirname "${ENV_FILE}")"
  cat > "${ENV_FILE}" <<EOF
# Generated by the Xulu installer — source from your shell to put xulu on PATH.
${PATH_LINE}
EOF
}

print_manual_path_help() {
  echo
  echo "Add this to $(default_rc_file) (or your shell config), then open a new terminal:"
  echo
  echo "  ${PATH_LINE}"
  echo
  echo "Or for this terminal only:"
  echo
  echo "  . ${ENV_FILE} && hash -r"
  echo
  echo "Note: on Ubuntu/Debian, ~/.profile may already add ~/.local/bin for login shells,"
  echo "but many terminals only load ~/.bashrc — so put the line there for reliability."
  echo
}

rc_has_install_dir() {
  local rc="$1"
  [[ -f "${rc}" ]] && grep -Fq "${INSTALL_DIR}" "${rc}"
}

append_path_to_rc() {
  local rc="$1"
  touch "${rc}"
  if rc_has_install_dir "${rc}"; then
    echo "PATH entry for ${INSTALL_DIR} already present in ${rc}."
    return 0
  fi
  {
    echo ""
    echo "# Xulu CLI"
    echo "${PATH_LINE}"
  } >> "${rc}"
  echo "Added PATH export to ${rc}."
}

maybe_configure_path() {
  local rc
  rc="$(default_rc_file)"

  write_env_file

  echo

  # Persist in the interactive shell rc (bashrc/zshrc). Checking only the current
  # PATH is not enough: login shells often get ~/.local/bin from ~/.profile, while
  # new terminal tabs typically only source ~/.bashrc and then miss xulu.
  if rc_has_install_dir "${rc}"; then
    echo "PATH for ${INSTALL_DIR} is already configured in ${rc}."
    if path_contains_install_dir; then
      echo "${INSTALL_DIR} is also on PATH in this shell."
    else
      echo "It is not on PATH in this shell yet."
    fi
    return 0
  fi

  if path_contains_install_dir; then
    echo "${INSTALL_DIR} is on PATH in this shell (often via ~/.profile),"
    echo "but new terminals may only load ${rc} and then miss xulu."
  else
    echo "Xulu is installed but ${INSTALL_DIR} is not on your PATH."
  fi
  echo

  if ask_yes_no "Add ${INSTALL_DIR} to PATH in ${rc}? [y/N] "; then
    append_path_to_rc "${rc}"
  else
    echo "Skipped automatic PATH update in ${rc}."
    print_manual_path_help
  fi
}

print_activate_hint() {
  echo
  echo "To use xulu in THIS terminal now, run:"
  echo
  echo "  . ${ENV_FILE} && hash -r"
  echo
  echo "Or use the recommended one-liner (install + activate):"
  echo
  echo "  curl -fsSL https://raw.githubusercontent.com/xuluhq/xulu/master/install.sh | bash && . ~/.local/share/xulu/env.sh && hash -r"
  echo
}

need_cmd curl
need_cmd uname
need_cmd mktemp

os="$(uname -s)"
arch="$(uname -m)"

if [[ "${os}" != "Linux" ]]; then
  echo "error: this installer currently supports Linux only (got ${os})" >&2
  exit 1
fi

if [[ "${arch}" != "x86_64" && "${arch}" != "amd64" ]]; then
  echo "error: this installer currently supports x86_64 only (got ${arch})" >&2
  exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

if [[ -n "${VERSION}" ]]; then
  # Accept v0.1.0 or 0.1.0
  tag="${VERSION}"
  [[ "${tag}" == v* ]] || tag="v${tag}"
  url="https://github.com/${REPO}/releases/download/${tag}/${ASSET}"
  echo "Downloading Xulu ${tag} (${ASSET})..."
else
  url="https://github.com/${REPO}/releases/latest/download/${ASSET}"
  echo "Downloading latest Xulu (${ASSET})..."
fi

curl -fsSL "${url}" -o "${tmpdir}/${ASSET}"
chmod +x "${tmpdir}/${ASSET}"

mkdir -p "${INSTALL_DIR}"
mv "${tmpdir}/${ASSET}" "${INSTALL_DIR}/xulu"

echo "Installed: ${INSTALL_DIR}/xulu"

maybe_configure_path

# Smoke-test inside this process only (does not affect the parent shell).
export PATH="${INSTALL_DIR}:${PATH}"
echo
if command -v xulu >/dev/null 2>&1; then
  xulu --help | head -n 5 || true
  echo
fi

print_activate_hint
echo "After activating PATH, run 'xulu --help' to get started."
