#!/usr/bin/env bash
# Install the Xulu CLI (Linux x86_64) from GitHub Releases.
#
#   curl -fsSL https://raw.githubusercontent.com/xuluhq/xulu/master/install.sh | bash
#
# Then either:
#   source ~/.local/share/xulu/env.sh
# or open a new terminal (if you answered y to the PATH prompt).
#
# Optional:
#   XULU_VERSION=v0.1.0 …     # pin a release tag
#   INSTALL_DIR=~/.local/bin … # custom install dir
#
# `curl | bash` runs in a child process and cannot change your interactive shell's
# PATH. That is why activation happens after install (source env.sh or a new terminal).

set -euo pipefail

REPO="xuluhq/xulu"
ASSET="xulu-linux-x86_64"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/.local/bin}"
VERSION="${XULU_VERSION:-}"
PATH_LINE="export PATH=\"${INSTALL_DIR}:\$PATH\""
ENV_FILE="${HOME}/.local/share/xulu/env.sh"

# Prefer writing user-facing messages to the terminal when stdin is the script pipe.
_out() {
  if [[ -r /dev/tty ]]; then
    # shellcheck disable=SC2059
    printf "$@" > /dev/tty
  else
    # shellcheck disable=SC2059
    printf "$@"
  fi
}

if [[ -r /dev/tty ]]; then
  BOLD=$'\033[1m'
  DIM=$'\033[2m'
  YELLOW=$'\033[33m'
  CYAN=$'\033[36m'
  RESET=$'\033[0m'
fi
BOLD="${BOLD:-}"
DIM="${DIM:-}"
YELLOW="${YELLOW:-}"
CYAN="${CYAN:-}"
RESET="${RESET:-}"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: '${1}' is required" >&2
    exit 1
  fi
}

path_contains_install_dir() {
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) return 0 ;;
    *) return 1 ;;
  esac
}

# Same behavior for bash and zsh users (SHELL selects the interactive rc file).
default_rc_file() {
  case "${SHELL##*/}" in
    zsh) echo "${HOME}/.zshrc" ;;
    bash) echo "${HOME}/.bashrc" ;;
    *) echo "${HOME}/.bashrc" ;;
  esac
}

ask_yes_no() {
  local prompt="$1"
  local reply
  if [[ -r /dev/tty ]]; then
    printf "%s" "${prompt}" > /dev/tty
    read -r reply < /dev/tty
  elif [[ -t 0 ]]; then
    printf "%s" "${prompt}"
    read -r reply
  else
    return 1
  fi
  case "${reply}" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

write_env_file() {
  mkdir -p "$(dirname "${ENV_FILE}")"
  cat > "${ENV_FILE}" <<EOF
# Generated by the Xulu installer (bash and zsh compatible).
# Usage:  . ${ENV_FILE}
${PATH_LINE}
EOF
}

rc_has_install_dir() {
  local rc="$1"
  [[ -f "${rc}" ]] && grep -Fq "${INSTALL_DIR}" "${rc}"
}

append_path_to_rc() {
  local rc="$1"
  touch "${rc}"
  if rc_has_install_dir "${rc}"; then
    _out '  PATH entry already present in %s\n' "${rc}"
    return 0
  fi
  {
    echo ""
    echo "# Xulu CLI"
    echo "${PATH_LINE}"
  } >> "${rc}"
  _out '  Added PATH export to %s\n' "${rc}"
}

print_box() {
  local title="$1"
  shift
  _out '\n'
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  _out '%s  %s%s%s\n' "${CYAN}" "${BOLD}" "${title}" "${RESET}"
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  local line
  for line in "$@"; do
    if [[ -z "${line}" ]]; then
      _out '\n'
    else
      _out '  %s\n' "${line}"
    fi
  done
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  _out '\n'
}

print_activate_next_steps() {
  print_box "IMPORTANT — use xulu in this terminal" \
    "curl | bash cannot change your current shell PATH." \
    "" \
    "Do ONE of the following:" \
    "" \
    "  1)  source ~/.local/share/xulu/env.sh" \
    "  2)  open a new terminal" \
    "" \
    "Then:  xulu --help"
}

print_manual_path_help() {
  local rc
  rc="$(default_rc_file)"
  _out '\nNote  Skipped editing %s.\n' "${rc}"
  _out '\n  Add this line to %s, then open a new terminal:\n\n' "${rc}"
  _out '    %s\n\n' "${PATH_LINE}"
  _out '  Or only for this terminal:\n\n'
  _out '    source %s\n\n' "${ENV_FILE}"
}

maybe_configure_path() {
  local rc
  rc="$(default_rc_file)"

  write_env_file

  _out '\n'

  if rc_has_install_dir "${rc}"; then
    _out 'PATH for %s is already configured in %s\n' "${INSTALL_DIR}" "${rc}"
    if path_contains_install_dir; then
      _out '  %sAlso available on PATH in this shell.%s\n' "${DIM}" "${RESET}"
    else
      _out '  %sNot on PATH in this shell yet — see next steps below.%s\n' "${DIM}" "${RESET}"
    fi
    return 0
  fi

  if path_contains_install_dir; then
    _out '%sNote%s  %s is on PATH in this shell (often via ~/.profile),\n' "${YELLOW}${BOLD}" "${RESET}" "${INSTALL_DIR}"
    _out '  but new terminals may only load %s and then miss xulu.\n' "${rc}"
  else
    _out '%sNote%s  Xulu is installed but %s is not on your PATH.\n' "${YELLOW}${BOLD}" "${RESET}" "${INSTALL_DIR}"
  fi
  _out '\n'

  if ask_yes_no "Add ${INSTALL_DIR} to PATH in ${rc}? [y/N] "; then
    append_path_to_rc "${rc}"
  else
    print_manual_path_help
  fi
}

need_cmd curl
need_cmd uname
need_cmd mktemp

os="$(uname -s)"
arch="$(uname -m)"

if [[ "${os}" != "Linux" ]]; then
  echo "error: this installer currently supports Linux only (got ${os})" >&2
  exit 1
fi

if [[ "${arch}" != "x86_64" && "${arch}" != "amd64" ]]; then
  echo "error: this installer currently supports x86_64 only (got ${arch})" >&2
  exit 1
fi

_out '\n%s── Xulu installer%s  (Linux x86_64 · bash & zsh)\n\n' "${BOLD}" "${RESET}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

if [[ -n "${VERSION}" ]]; then
  tag="${VERSION}"
  [[ "${tag}" == v* ]] || tag="v${tag}"
  url="https://github.com/${REPO}/releases/download/${tag}/${ASSET}"
  _out 'Downloading Xulu %s (%s)...\n' "${tag}" "${ASSET}"
else
  url="https://github.com/${REPO}/releases/latest/download/${ASSET}"
  _out 'Downloading latest Xulu (%s)...\n' "${ASSET}"
fi

curl -fsSL "${url}" -o "${tmpdir}/${ASSET}"

# Verify checksum when the companion .sha256 asset is available.
sum_url="${url}.sha256"
if curl -fsSL "${sum_url}" -o "${tmpdir}/${ASSET}.sha256"; then
  (
    cd "${tmpdir}"
    if command -v sha256sum >/dev/null 2>&1; then
      sha256sum -c "${ASSET}.sha256"
    else
      echo "warning: sha256sum not found; skipped checksum verification" >&2
    fi
  )
else
  echo "warning: could not download ${ASSET}.sha256; skipped checksum verification" >&2
fi

chmod +x "${tmpdir}/${ASSET}"

mkdir -p "${INSTALL_DIR}"
mv "${tmpdir}/${ASSET}" "${INSTALL_DIR}/xulu"

_out 'Installed %s\n' "${INSTALL_DIR}/xulu"

maybe_configure_path
print_activate_next_steps

_out 'Later updates:  xulu update\n'
_out 'Check only:     xulu update --check\n\n'
