#!/usr/bin/env bash
# Install the Xulu CLI (Linux / macOS) from GitHub Releases.
#
#   curl -fsSL https://raw.githubusercontent.com/xuluhq/xulu/master/install.sh | bash
#
# Then either:
#   source ~/.local/share/xulu/env.sh
# or open a new terminal (if you answered y to the PATH prompt).
#
# Optional:
#   XULU_VERSION=v0.1.0 …              # pin a release tag
#   XULU_PLATFORM=linux-aarch64 …      # override auto-detect
#   INSTALL_DIR=~/.local/bin …         # custom install dir
#
# Override platform when piping:
#   curl -fsSL …/install.sh | bash -s -- --platform darwin-aarch64
#
# Supported platforms:
#   linux-x86_64 | linux-aarch64 | darwin-aarch64
#   (macOS Intel / darwin-x86_64 planned)
#
# `curl | bash` runs in a child process and cannot change your interactive shell's
# PATH. That is why activation happens after install (source env.sh or a new terminal).

set -euo pipefail

REPO="xuluhq/xulu"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/.local/bin}"
VERSION="${XULU_VERSION:-}"
PLATFORM="${XULU_PLATFORM:-}"
PATH_LINE="export PATH=\"${INSTALL_DIR}:\$PATH\""
ENV_FILE="${HOME}/.local/share/xulu/env.sh"

# Prefer writing user-facing messages to the terminal when stdin is the script pipe.
_out() {
  if [[ -r /dev/tty ]]; then
    # shellcheck disable=SC2059
    printf "$@" > /dev/tty
  else
    # shellcheck disable=SC2059
    printf "$@"
  fi
}

if [[ -r /dev/tty ]]; then
  BOLD=$'\033[1m'
  DIM=$'\033[2m'
  YELLOW=$'\033[33m'
  CYAN=$'\033[36m'
  RESET=$'\033[0m'
fi
BOLD="${BOLD:-}"
DIM="${DIM:-}"
YELLOW="${YELLOW:-}"
CYAN="${CYAN:-}"
RESET="${RESET:-}"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: '${1}' is required" >&2
    exit 1
  fi
}

path_contains_install_dir() {
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) return 0 ;;
    *) return 1 ;;
  esac
}

# Same behavior for bash and zsh users (SHELL selects the interactive rc file).
default_rc_file() {
  case "${SHELL##*/}" in
    zsh) echo "${HOME}/.zshrc" ;;
    bash) echo "${HOME}/.bashrc" ;;
    *) echo "${HOME}/.bashrc" ;;
  esac
}

ask_yes_no() {
  local prompt="$1"
  local reply
  if [[ -r /dev/tty ]]; then
    printf "%s" "${prompt}" > /dev/tty
    read -r reply < /dev/tty
  elif [[ -t 0 ]]; then
    printf "%s" "${prompt}"
    read -r reply
  else
    return 1
  fi
  case "${reply}" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

write_env_file() {
  mkdir -p "$(dirname "${ENV_FILE}")"
  cat > "${ENV_FILE}" <<EOF
# Generated by the Xulu installer (bash and zsh compatible).
# Usage:  . ${ENV_FILE}
${PATH_LINE}
EOF
}

rc_has_install_dir() {
  local rc="$1"
  [[ -f "${rc}" ]] && grep -Fq "${INSTALL_DIR}" "${rc}"
}

append_path_to_rc() {
  local rc="$1"
  touch "${rc}"
  if rc_has_install_dir "${rc}"; then
    _out '  PATH entry already present in %s\n' "${rc}"
    return 0
  fi
  {
    echo ""
    echo "# Xulu CLI"
    echo "${PATH_LINE}"
  } >> "${rc}"
  _out '  Added PATH export to %s\n' "${rc}"
}

print_box() {
  local title="$1"
  shift
  _out '\n'
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  _out '%s  %s%s%s\n' "${CYAN}" "${BOLD}" "${title}" "${RESET}"
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  local line
  for line in "$@"; do
    if [[ -z "${line}" ]]; then
      _out '\n'
    else
      _out '  %s\n' "${line}"
    fi
  done
  _out '%s━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━%s\n' "${CYAN}" "${RESET}"
  _out '\n'
}

print_activate_next_steps() {
  print_box "IMPORTANT — use xulu in this terminal" \
    "curl | bash cannot change your current shell PATH." \
    "" \
    "Do ONE of the following:" \
    "" \
    "  1)  source ~/.local/share/xulu/env.sh" \
    "  2)  open a new terminal" \
    "" \
    "Then:  xulu --help"
}

print_manual_path_help() {
  local rc
  rc="$(default_rc_file)"
  _out '\nNote  Skipped editing %s.\n' "${rc}"
  _out '\n  Add this line to %s, then open a new terminal:\n\n' "${rc}"
  _out '    %s\n\n' "${PATH_LINE}"
  _out '  Or only for this terminal:\n\n'
  _out '    source %s\n\n' "${ENV_FILE}"
}

maybe_configure_path() {
  local rc
  rc="$(default_rc_file)"

  write_env_file

  _out '\n'

  if rc_has_install_dir "${rc}"; then
    _out 'PATH for %s is already configured in %s\n' "${INSTALL_DIR}" "${rc}"
    if path_contains_install_dir; then
      _out '  %sAlso available on PATH in this shell.%s\n' "${DIM}" "${RESET}"
    else
      _out '  %sNot on PATH in this shell yet — see next steps below.%s\n' "${DIM}" "${RESET}"
    fi
    return 0
  fi

  if path_contains_install_dir; then
    _out '%sNote%s  %s is on PATH in this shell (often via ~/.profile),\n' "${YELLOW}${BOLD}" "${RESET}" "${INSTALL_DIR}"
    _out '  but new terminals may only load %s and then miss xulu.\n' "${rc}"
  else
    _out '%sNote%s  Xulu is installed but %s is not on your PATH.\n' "${YELLOW}${BOLD}" "${RESET}" "${INSTALL_DIR}"
  fi
  _out '\n'

  if ask_yes_no "Add ${INSTALL_DIR} to PATH in ${rc}? [y/N] "; then
    append_path_to_rc "${rc}"
  else
    print_manual_path_help
  fi
}

usage() {
  cat <<EOF >&2
Usage: install.sh [--platform linux-x86_64|linux-aarch64|darwin-aarch64]

Auto-detects Linux (x86_64 / arm64) or macOS Apple Silicon. Override with --platform or XULU_PLATFORM.
macOS Intel is not available yet.
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --platform)
        if [[ $# -lt 2 ]]; then
          echo "error: --platform requires a value (linux-x86_64, linux-aarch64, or darwin-aarch64)" >&2
          exit 1
        fi
        PLATFORM="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "error: unknown argument: $1" >&2
        usage
        exit 1
        ;;
    esac
  done
}

normalize_platform() {
  # tr instead of ${var,,} so macOS system bash 3.2 works.
  local p
  p="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"
  case "${p}" in
    linux-x86_64|x86_64|amd64|x64) printf '%s' "linux-x86_64" ;;
    linux-aarch64|aarch64|arm64) printf '%s' "linux-aarch64" ;;
    darwin-aarch64|macos-aarch64|macos-arm64|darwin-arm64) printf '%s' "darwin-aarch64" ;;
    darwin-x86_64|macos-x86_64|macos-amd64|darwin-amd64)
      echo "error: macOS Intel binaries are not published yet (planned). Apple Silicon is supported via darwin-aarch64." >&2
      exit 1
      ;;
    *)
      echo "error: unsupported platform '${1}' (use linux-x86_64, linux-aarch64, or darwin-aarch64)" >&2
      exit 1
      ;;
  esac
}

asset_for_platform() {
  case "$1" in
    linux-x86_64) printf '%s' "xulu-linux-x86_64" ;;
    linux-aarch64) printf '%s' "xulu-linux-aarch64" ;;
    darwin-aarch64) printf '%s' "xulu-darwin-aarch64" ;;
    *)
      echo "error: internal error: unknown platform '$1'" >&2
      exit 1
      ;;
  esac
}

platform_label() {
  case "$1" in
    linux-x86_64) printf '%s' "Linux x86_64" ;;
    linux-aarch64) printf '%s' "Linux arm64" ;;
    darwin-aarch64) printf '%s' "macOS Apple Silicon" ;;
    *) printf '%s' "$1" ;;
  esac
}

detect_platform() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "${os}" in
    Linux)
      case "${arch}" in
        x86_64|amd64) printf '%s' "linux-x86_64" ;;
        aarch64|arm64) printf '%s' "linux-aarch64" ;;
        *)
          echo "error: unsupported Linux architecture '${arch}' (supported: x86_64, arm64)" >&2
          exit 1
          ;;
      esac
      ;;
    Darwin)
      case "${arch}" in
        arm64) printf '%s' "darwin-aarch64" ;;
        x86_64|amd64)
          echo "error: macOS Intel binaries are not published yet (planned). Apple Silicon (arm64) is supported." >&2
          exit 1
          ;;
        *)
          echo "error: unsupported macOS architecture '${arch}' (Apple Silicon arm64 is supported)" >&2
          exit 1
          ;;
      esac
      ;;
    *)
      echo "error: this installer supports Linux and macOS Apple Silicon only (got ${os})" >&2
      exit 1
      ;;
  esac
}

verify_sha256() {
  local asset="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum -c "${asset}.sha256"
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 -c "${asset}.sha256"
  else
    echo "warning: neither sha256sum nor shasum found; skipped checksum verification" >&2
  fi
}

parse_args "$@"

need_cmd curl
need_cmd uname
need_cmd mktemp

if [[ -n "${PLATFORM}" ]]; then
  PLATFORM="$(normalize_platform "${PLATFORM}")"
else
  PLATFORM="$(detect_platform)"
fi

ASSET="$(asset_for_platform "${PLATFORM}")"
PLATFORM_LABEL="$(platform_label "${PLATFORM}")"

_out '\n%s── Xulu installer%s  (%s · bash & zsh)\n\n' "${BOLD}" "${RESET}" "${PLATFORM_LABEL}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

resolve_latest_tag() {
  # Prefer the release API so we can print the exact version being installed.
  local json
  if ! json="$(curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    -H "User-Agent: xulu-install" \
    "https://api.github.com/repos/${REPO}/releases/latest")"; then
    echo "error: could not resolve latest release for ${REPO}" >&2
    exit 1
  fi
  local tag
  tag="$(printf '%s' "${json}" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)"
  if [[ -z "${tag}" ]]; then
    echo "error: could not parse tag_name from GitHub latest release response" >&2
    exit 1
  fi
  printf '%s\n' "${tag}"
}

if [[ -n "${VERSION}" ]]; then
  tag="${VERSION}"
  [[ "${tag}" == v* ]] || tag="v${tag}"
else
  tag="$(resolve_latest_tag)"
fi

url="https://github.com/${REPO}/releases/download/${tag}/${ASSET}"
_out 'Installing Xulu %s (%s)...\n' "${tag}" "${ASSET}"

curl -fsSL "${url}" -o "${tmpdir}/${ASSET}"

# Verify checksum when the companion .sha256 asset is available.
sum_url="${url}.sha256"
if curl -fsSL "${sum_url}" -o "${tmpdir}/${ASSET}.sha256"; then
  (
    cd "${tmpdir}"
    verify_sha256 "${ASSET}"
  )
else
  echo "warning: could not download ${ASSET}.sha256; skipped checksum verification" >&2
fi

chmod +x "${tmpdir}/${ASSET}"

mkdir -p "${INSTALL_DIR}"
mv "${tmpdir}/${ASSET}" "${INSTALL_DIR}/xulu"

_out 'Installed %s\n' "${INSTALL_DIR}/xulu"
_out 'Release:   %s\n' "${tag}"
if reported="$("${INSTALL_DIR}/xulu" --version 2>/dev/null)"; then
  _out 'Binary:    %s\n' "${reported}"
fi

maybe_configure_path
print_activate_next_steps

_out 'Later updates:  xulu update\n'
_out 'Check only:     xulu update --check\n'
_out 'Show version:   xulu -v\n\n'
