# Install the Xulu CLI (Windows x86_64) from GitHub Releases.
#
#   irm https://raw.githubusercontent.com/xuluhq/xulu/master/install.ps1 | iex
#
# Optional environment variables:
#   $env:XULU_VERSION = "v0.2.13"           # pin a release tag
#   $env:XULU_PLATFORM = "windows-x86_64"   # override auto-detect
#   $env:INSTALL_DIR = "$HOME\.local\bin"   # custom install dir
#
# Installs to ~/.local/bin/xulu.exe by default, writes ~/.local/share/xulu/env.ps1,
# and offers to add that dir to the user PATH. Prefer this script over a browser
# download of the .exe.
#
# Activate in the current PowerShell session (like source on Unix):
#   . $HOME\.local\share\xulu\env.ps1


$ErrorActionPreference = "Stop"

$Repo = "xuluhq/xulu"
$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { Join-Path $HOME ".local\bin" }
$Version = $env:XULU_VERSION
$Platform = $env:XULU_PLATFORM
$EnvFile = Join-Path $HOME ".local\share\xulu\env.ps1"

function Write-Info([string]$Message) {
    Write-Host $Message
}

function Resolve-Platform {
    param([string]$Override)

    if ($Override) {
        $p = $Override.ToLowerInvariant()
        switch ($p) {
            { $_ -in @("windows-x86_64", "windows-amd64", "x86_64", "amd64") } {
                return "windows-x86_64"
            }
            { $_ -in @("windows-aarch64", "windows-arm64", "aarch64", "arm64") } {
                throw "Windows ARM64 binaries are not published yet (planned). x86_64 is supported."
            }
            default {
                throw "Unsupported platform '$Override' (use windows-x86_64)."
            }
        }
    }

    if ($env:OS -ne "Windows_NT") {
        throw "This installer supports Windows only (got OS='$env:OS')."
    }

    switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture) {
        "X64" { return "windows-x86_64" }
        "Arm64" {
            throw "Windows ARM64 binaries are not published yet (planned). x86_64 is supported."
        }
        default {
            throw "Unsupported Windows architecture '$(([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture))'."
        }
    }
}

function Get-AssetName([string]$PlatformName) {
    switch ($PlatformName) {
        "windows-x86_64" { return "xulu-windows-x86_64.exe" }
        default { throw "Internal error: unknown platform '$PlatformName'" }
    }
}

function Get-PlatformLabel([string]$PlatformName) {
    switch ($PlatformName) {
        "windows-x86_64" { return "Windows x86_64" }
        default { return $PlatformName }
    }
}

function Get-LatestTag {
    $headers = @{
        "Accept"     = "application/vnd.github+json"
        "User-Agent" = "xulu-install"
    }
    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" -Headers $headers
    if (-not $release.tag_name) {
        throw "Could not parse tag_name from GitHub latest release response."
    }
    return [string]$release.tag_name
}

function Test-PathContainsInstallDir {
    $parts = ($env:Path -split ";") | ForEach-Object { $_.TrimEnd("\") }
    $target = $InstallDir.TrimEnd("\")
    return [bool]($parts | Where-Object { $_ -eq $target })
}

function Write-EnvFile {
    $dir = Split-Path -Parent $EnvFile
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    # Dot-source in this session:  . $HOME\.local\share\xulu\env.ps1
    $content = @"
# Generated by the Xulu installer (PowerShell).
# Usage:  . $EnvFile
`$xuluBin = '$InstallDir'
`$parts = (`$env:Path -split ';') | ForEach-Object { `$_.TrimEnd('\') }
if (-not (`$parts -contains `$xuluBin.TrimEnd('\'))) {
  `$env:Path = "`$xuluBin;`$env:Path"
}
"@
    Set-Content -Path $EnvFile -Value $content -Encoding UTF8
}

function Add-InstallDirToSessionPath {
    if (-not (Test-PathContainsInstallDir)) {
        $env:Path = "$InstallDir;$env:Path"
    }
}

function Add-InstallDirToUserPath {
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if (-not $userPath) { $userPath = "" }
    $parts = ($userPath -split ";") | Where-Object { $_ -ne "" }
    $target = $InstallDir.TrimEnd("\")
    if ($parts | Where-Object { $_.TrimEnd("\") -eq $target }) {
        Write-Info "  PATH entry already present in the user environment."
        return
    }
    $newPath = if ($userPath.Trim() -eq "") { $InstallDir } else { "$userPath;$InstallDir" }
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    Write-Info "  Added $InstallDir to the user PATH."
}

function Show-ActivateNextSteps {
    Write-Host ""
    Write-Info "IMPORTANT - use xulu in this terminal"
    Write-Info "  Do ONE of the following:"
    Write-Info "    1)  . $EnvFile"
    Write-Info "    2)  open a new terminal (after user PATH was updated)"
    Write-Info "  Then:  xulu --help"
}

$Platform = Resolve-Platform -Override $Platform
$Asset = Get-AssetName $Platform
$PlatformLabel = Get-PlatformLabel $Platform

Write-Host ""
Write-Info "── Xulu installer  ($PlatformLabel · PowerShell)"
Write-Host ""

if ($Version) {
    $tag = $Version
    if (-not $tag.StartsWith("v")) { $tag = "v$tag" }
} else {
    $tag = Get-LatestTag
}

$url = "https://github.com/$Repo/releases/download/$tag/$Asset"
$sumUrl = "$url.sha256"
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("xulu-install-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null

try {
    Write-Info "Installing Xulu $tag ($Asset)..."
    $binPath = Join-Path $tmp $Asset
    $sumPath = Join-Path $tmp "$Asset.sha256"
    Invoke-WebRequest -Uri $url -OutFile $binPath -UseBasicParsing

    try {
        Invoke-WebRequest -Uri $sumUrl -OutFile $sumPath -UseBasicParsing
        $sumLine = (Get-Content -Path $sumPath -Raw).Trim()
        $expected = ($sumLine -split "\s+")[0].ToLowerInvariant()
        $actual = (Get-FileHash -Algorithm SHA256 -Path $binPath).Hash.ToLowerInvariant()
        if ($expected -ne $actual) {
            throw "Checksum mismatch for ${Asset}: expected ${expected}, got ${actual}"
        }
        Write-Info "Checksum OK."
    } catch {
        if ($_.Exception.Message -like "Checksum mismatch*") { throw }
        Write-Warning "Could not verify checksum; continuing without verification. $($_.Exception.Message)"
    }

    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $dest = Join-Path $InstallDir "xulu.exe"
    Copy-Item -Force -Path $binPath -Destination $dest

    Write-Info "Installed $dest"
    Write-Info "Release:   $tag"
    try {
        $reported = & $dest --version 2>$null
        if ($reported) { Write-Info "Binary:    $reported" }
    } catch {
        # ignore version probe failures
    }

    Write-EnvFile
    Add-InstallDirToSessionPath

    Write-Host ""
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $userParts = if ($userPath) { ($userPath -split ";") | ForEach-Object { $_.TrimEnd("\") } } else { @() }
    $target = $InstallDir.TrimEnd("\")
    if ($userParts -contains $target) {
        Write-Info "PATH for $InstallDir is already configured in the user environment."
    } else {
        Write-Info "Note  $InstallDir is not on your user PATH yet (new terminals may miss xulu)."
        $answer = Read-Host "Add $InstallDir to the user PATH? [y/N]"
        if ($answer -match '^(y|yes)$') {
            Add-InstallDirToUserPath
        } else {
            Write-Host ""
            Write-Info "Skipped editing the user PATH."
            Write-Info "  For this terminal:  . $EnvFile"
            Write-Info "  Or add permanently:  $InstallDir"
        }
    }

    Show-ActivateNextSteps
    Write-Info "Later updates:  xulu update"
    Write-Info "Check only:     xulu update --check"
    Write-Host ""
} finally {
    Remove-Item -Recurse -Force -Path $tmp -ErrorAction SilentlyContinue
}
